backend:
  name: github
  repo: SimonSiefke/gatsby-netlify-cms
  branch: master

media_folder: "public/static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: Question, name: question, widget: markdown}
      - {label: Answer, name: answer, widget: markdown}
      # - {label: Title, name: title, widget: string, tagname:h1}
